### ISSUE TITLE
There are some errors raised when I run it following the readme.

### ISSUE THREAD

**Issue by jane00** [material-motion/direct#6]
Traceback (most recent call last):
  File "/Users/admin/Documents/google-cloud-sdk/platform/google_appengine/lib/cherrypy/cherrypy/wsgiserver/wsgiserver2.py", line 1302, in communicate
    req.respond()
  File "/Users/admin/Documents/google-cloud-sdk/platform/google_appengine/lib/cherrypy/cherrypy/wsgiserver/wsgiserver2.py", line 831, in respond
    self.server.gateway(self).respond()
  File "/Users/admin/Documents/google-cloud-sdk/platform/google_appengine/lib/cherrypy/cherrypy/wsgiserver/wsgiserver2.py", line 2115, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/Users/admin/Documents/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 292, in __call__
    return app(environ, start_response)
  File "/Users/admin/Documents/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/request_rewriter.py", line 314, in _rewriter_middleware
    response_body = iter(application(environ, wrapped_start_response))
  File "/Users/admin/Documents/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/request_handler.py", line 165, in __call__
    self._flush_logs(response.get('logs', []))
  File "/Users/admin/Documents/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/request_handler.py", line 308, in _flush_logs
    apiproxy_stub_map.MakeSyncCall('logservice', 'Flush', request, response)
  File "/Users/admin/Documents/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 97, in MakeSyncCall
    return stubmap.MakeSyncCall(service, call, request, response)
  File "/Users/admin/Documents/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 331, in MakeSyncCall
    rpc.CheckSuccess()
  File "/Users/admin/Documents/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_rpc.py", line 136, in CheckSuccess
    self._traceback)
  File "/Users/admin/Documents/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_rpc.py", line 161, in _WaitImpl
    self.request, self.response)
  File "/Users/admin/Documents/google-cloud-sdk/platform/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 223, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/Users/admin/Documents/google-cloud-sdk/platform/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 248, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/Users/admin/Documents/google-cloud-sdk/platform/google_appengine/google/appengine/tools/appengine_rpc.py", line 469, in Send
    f = self.opener.open(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable

**Comment by jane00** [comment]
OK, the answer is bellow.
https://stackoverflow.com/questions/16698621/google-app-engine-error-httperror/19460147#19460147
